import subprocess
import os


#By xxseva44@XDA
#########################################################################################################
def TextBreak ():
	print("#############################")
	print("#############################")

def Rom_Check ():
	global Rom
	Rom = input("What rom are you building \n")

def Android_Version ():
	global AndroidVersion
	AndroidVersion = int(input("What version of android are you building? \n"))

def Thread_Check():
	global Thread
	Thread = input("How many threads does your cpu have? \n")


def Working_DirCheck ():
	subprocess.call(['pwd'])
	DirCon = input("is this the correct directory? Y/N \n")
	if DirCon == "Y":
		print("Directory set")
	elif DirCon == "N":
		DirSelect()
	else:
		print("Please choose a valid option!!! \n")
		Working_DirCheck()


def DirSelect ():
	os.chdir("/home")
	subprocess.call(['pwd'])
	Dir = input("Please enter the working directory \n")
	os.chdir(Dir)
	print (f"{Dir} is now selected!")


def Ccache_Config ():
	CcacheCon = input("Enable ccache? Y/N \n")
	if CcacheCon == "Y":
		os.system("export USE_CCACHE=1")
		CcacheSpace = input("How much space would you like too allocate in gigabytes? Ex. 50G \n")
		os.system("ccache -M" + CcacheSpace)
	elif CcacheCon == "N":
		subprocess.run('export USE_CCACHE=0')


def DeviceVariant_BuildConfig ():
	global DeviceVar
	DeviceVar = input("What device/variant would you like to build? \n")

def Build_Details():
	print(f"Building {Rom} {AndroidVersion} for {DeviceVar}")
	f = open("BSAddons/temp/BuildConf.txt", "w")
	f.write("This file is automatically generated!! \n")
	f.write("Build command debug: \n")
	f.write(f"lunch {Rom}_{DeviceVar}-{BuildType} \n")
	f = open("BSAddons/temp/BuildConfR.txt", "w")
	f.write(f"{Rom} \n")
	f = open("BSAddons/temp/BuildConfD.txt", "w")
	f.write(f"{DeviceVar} \n")
	f = open("BSAddons/temp/BuildConfB.txt", "w")
	f.write(f"{BuildType} \n")
	f = open("BSAddons/temp/BuildConfA.txt", "w")
	f.write(f"{AndroidVersion} \n")
	f = open("BSAddons/temp/BuildConfT.txt", "w")
	f.write(f"{Thread} \n")


def Build_Type ():
	print("What build would you like to make?")
	global BuildType
	BuildType = input("Options: user|userdebug|eng \n")


def Start_Build ():
	print("Starting Build")
	print("Please wait...")
	print("This may take a while...")


print("########################")
print("#Automated Build Script#")
print("#By:   XXSEVA44@XDA    #")
print("########################")
#Working_DirCheck()
Rom_Check()
Android_Version ()
TextBreak()
subprocess.call( "./BSAddons/SetBuildEnv.sh", shell=True)
TextBreak()
#Ccache_Config()
Thread_Check()
Build_Type()
TextBreak()
DeviceVariant_BuildConfig()
TextBreak()
Build_Details()
subprocess.call( "./BSAddons/LunchBuild.sh", shell=True)
Start_Build()
subprocess.call( "./BSAddons/StartBuild.sh", shell=True)
